@startuml
skin rose
set separator none
!pragma useIntermediatePackages false
package Users.IdeaProjects.Taller2PA{
    package Model{
        abstract Entidad <<abstract>> {
            +getNombreUsuario(): String
            +setNombreUusario(nombreUsuario: String): void
            +getEmail(): String
            +setEmail(email: String): void
            +getContrasenia(): String
            +setContrasenia(contrasenia: String): void
            +getTipoPerfil(): String
            +setTipoPerfil(tipoPerfil: String): void
            +getUbicacion(): String
            +setUbicacion(ubicacion: String): String
            +gestionarSolicitudes(perfiles: Perfil[], usuario: Perfil): void
            +agregarAmigoIndirectamente(solicitud: Perfil, usuario: Perfil): void
            +agregarAmigo(solicitud: Perfil, perfiles: Perfil[], usuario: Perfil): void
            +eliminarAmigo(amigoEliminar: String): boolean
            +eliminarSolicitud(solicitud: Perfil): void
            +agregarSolicitud(solcitud: Perfil): void
            +verListaDeAmigos(): void
            +verListaDeMensajesEnviados(): void
            +agregarMensajeEnviado(mensaje: Mensaje): void
            +verListaDeMensajesRecibidos(): void
            +agregarMensajeRecibido(mensaje: Mensaje): void
            +desplegarPerfil(): void
            +buscarAmigo(amigoBuscado: String): boolean
        }
        class Perfil {
            -nombreUsuario: String
            -email: String
            -contrasenia: String
            -tipoPerfil: String
            -ubicacion: String
            -amigos: LinkedList<Perfil>
            -listaDeSolicitudes: LinkedList<Perfil>
            -mensajesRecibidos: ArrayList<Mensaje>
            -mensajesEnviados: ArrayList<Mensaje>
            +Perfil(nombreUsuario: String, email: String, contrasenia: String, tipoPerfil: String, ubicacion: String)
        }

        class Solicitud {
            -destinatario: Perfil
            -estado: String
            -fechaDeCreacion: String
            -ultimaActualizacion: String
            +Solicitud(remitente: Perfil, destinatario: Perfil)
            +getEstado(): String
            +setEstado(actualizacionEstado: String): void
            +getFechaDeCreacion(): String
            +getUltimaActualizacion(): String
            +setUltimaActualizacion(): void
            +desplegarSolicitud(): void
        }

        class Mensaje {
            -destinatario: Perfil
            -contenido: String
            -horaDeEnvio: String
            -fechaDeEnvio: String
            +Mensaje(remitente: Perfil, destinatario: Perfil, contenido: String)
            +desplegarMensajeEnviado(): void
            +desplegarMensajeRecibido(): void
        }
        Perfil "1" --> "0..*" Mensaje: -remitente: Perfil
        Perfil "1" --> "0..*" Solicitud: -remitente: Perfil
        Entidad "1" <|-- "1" Perfil
    }
    package Services{
        interface Sistema{
            +cargarInformacion(): void
            +ejecucionGeneral(): void
            +iniciarSesion(): void
            +registroNuevo(): void
            +enviarSolicitud(): void
            +enviarMensaje(): void
            +verMensajes(): void
            +buscarUsuario(): void
            +menuSesionIniciada(): void
            +actualizarInformacion(): void
            +menuPerfil(): void
            +buscarPerfil():void
            +buscarPerfilTipo(): void
            +buscarPerfilNombre(): void
            +buscarPerfilUbicacion(): void
            +editarTipoPerfil():void
            +editarUbicacion(): void
            +editarCorreo(): void
            +editarContrasenia(): void
            +editarNombre(): void
            +menuSolicitud(): void
            +eliminarAmigo(): void
            +agregarAmigo(): void
            +menuMensaje(): void
            +verMensajesEnviados(): void
            +verMensajesRecibidos(): void
        }

        class SistemaImpl{
            -GSON: Gson
            -ciudades: LinkedList<String>
            -usuario: Perfil
        }
        Sistema "1" .|> "1" SistemaImpl
        SistemaImpl "1" -> "0..*" Perfil: +perfiles: LinkedList<Perfil>
    }
    package Util{
        class Utils{
            -EMAIL_PATTERN: Pattern
            -Utils()
            +append(theStaticArray: T[], the object: T[]): T[]
            +validarEmail(email: String): void
        }
        SistemaImpl "1"<--"1" Utils
    }
}

@enduml